common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views

app_name = 'pybo'

urlpatterns = [
     # base_views.py
     path('',
          base_views.index, name='index'),
     path('<int:question_id>/',
          base_views.detail, name='detail'),

     # question_views.py
     path('question/create/',
          question_views.question_create, name='question_create'),
     path('question/modify/<int:question_id>/',
          question_views.question_modify, name='question_modify'),
     path('question/delete/<int:question_id>/',
          question_views.question_delete, name='question_delete'),

     # answer_views.py
     path('answer/create/<int:question_id>/',
          answer_views.answer_create, name='answer_create'),
     path('answer/modify/<int:answer_id>/',
          answer_views.answer_modify, name='answer_modify'),
     path('answer/delete/<int:answer_id>/',
          answer_views.answer_delete, name='answer_delete'),

     # comment_views.py
     path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
     path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
     path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
     path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
     path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
     path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

     path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
     path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote')
]

pybo/views/base_views.py
from django.db.models import Q, Count
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from ..models import Question

# Create your views here.
def index(request):
    # 입력인자
    page = request.GET.get('page', 1)
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')
    ca = request.GET.get('ca', '0')

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(
            num_voter = Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(
            num_answer = Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')

    #카테고리
    if ca and ca != '0':
        question_list = question_list.filter(
            Q(category__pk__icontains=ca)
        ).distinct()

    # 조회
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()
    
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so, 'ca': ca}

    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """
    pybo 목록 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    so = request.GET.get('so', 'recent')
    is_view = request.GET.get('is_view', 0)

    if is_view == 0:
        question.views += 1
        question.save()

    if so == 'recommend':
        answer_list = question.answer_set.annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    else:
        answer_list = question.answer_set.order_by('-create_date')

    context = {'question': question, 'answer_list': answer_list, 'so': so, 'is_view': 1}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <!-- pybo CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title>파이보</title>
    </head>
    <body>
        <!-- 네비게이션바 -->
        {% include "navbar.html" %}

        <!-- 기본 템플릿 안에 삽입될 내용 Start -->
        {% block content %}
        {% endblock %}
        <!-- 기본 템플릿 안에 삽입될 내용 -->

    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>

    {% block script %}
    {% endblock %}
    </body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in from.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-toggle="collapse"
                data-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>